
var numToUrl = {
    1: "https://www.youtube.com/watch?v=bNQSMTNSnUw",
    2: "https://www.youtube.com/watch?v=SC8cSnFTd_0",
    3: "https://www.youtube.com/watch?v=Oqz2QNV58fw",
    4: "https://www.youtube.com/watch?v=w3viBe2Q0P8",
    5: "https://www.youtube.com/watch?v=qdpXxGPqW-Y",
    6: "https://www.youtube.com/watch?v=E3x_dLVTEuA",
    7: "https://www.youtube.com/watch?v=n8X9_MgEdCg",
    8: "https://www.youtube.com/watch?v=gRC30wQG79A",
    9: "https://www.youtube.com/watch?v=W0DM5lcj6mw",
    10: "https://www.youtube.com/watch?v=wL8DVHuWI7Y",
    11: "https://www.youtube.com/watch?v=WgTMeICssXY",
    12: "https://www.youtube.com/watch?v=2lh_fR6aiL0",
    13: "https://www.youtube.com/watch?v=7KPyunRIjr0",
    14: "https://www.youtube.com/watch?v=lYoWuaw5nSk",
    15: "https://www.youtube.com/watch?v=BZcErUf7S_8",
    16: "https://www.youtube.com/watch?v=K41REhBIfAQ",
    17: "https://www.youtube.com/watch?v=J_DV9b0x7v4",
    18: "https://www.youtube.com/watch?v=zrwTYozyzYA",
    19: "https://www.youtube.com/watch?v=vu70X3e_83I",
    20: "https://www.youtube.com/watch?v=u3JrJBYlJNo",
    21: "https://www.youtube.com/watch?v=uu7j_xljCRY",
    22: "https://www.youtube.com/watch?v=jvipPYFebWc",
    23: "https://www.youtube.com/watch?v=Kqe883Fc0Bk",
    24: "https://www.youtube.com/watch?v=vj-x3FSUmVc",
    25: "https://www.youtube.com/watch?v=lcg6wekmCRA",
    26: "https://www.youtube.com/watch?v=kGn13Apz8Tg",
    27: "https://www.youtube.com/watch?v=Vopbz-exbfg",
    28: "https://www.youtube.com/watch?v=ro-gE1LEZ5E",
    29: "https://www.youtube.com/watch?v=oPA0z4W-kcU",
    30: "https://www.youtube.com/watch?v=Y4o_8zbelwY",
    31: "https://www.youtube.com/watch?v=qHDJSRlNhVs",
    32: "https://www.youtube.com/watch?v=XsZZQPKLChY",
    33: "https://www.youtube.com/watch?v=e4-raurU5zI",
    34: "https://www.youtube.com/watch?v=3fxq7kqyWO8",
    35: "https://www.youtube.com/watch?v=C5lq1YxkVvg",
    36: "https://www.youtube.com/watch?v=9iHM6X6uUH8",
    37: "https://www.youtube.com/watch?v=yD0bEMqxYbM",
    38: "https://www.youtube.com/watch?v=4Q46xYqUwZQ",
    39: "https://www.youtube.com/watch?v=LkIWmsP3c_s",
    40: "https://www.youtube.com/watch?v=eE9tV1WGTgE",
    41: "https://www.youtube.com/watch?v=6BSfBEAAWEc",
    42: "https://www.youtube.com/watch?v=51u5fnyrGj4",
    43: "https://www.youtube.com/watch?v=L0MK7qz13bU",
    44: "https://www.youtube.com/watch?v=6yvfU8xK_VQ",
    45: "https://www.youtube.com/watch?v=qjlVAsvQLM8",
    46: "https://www.youtube.com/watch?v=hT_nvWreIhg",
    47: "https://www.youtube.com/watch?v=sVx1mJDeUjY",
    48: "https://www.youtube.com/watch?v=6bALJxjL8jw",
    49: "https://www.youtube.com/watch?v=XzilCu9PcZk",
    50: "https://www.youtube.com/watch?v=1-xGerv5FOk",
    51: "https://www.youtube.com/watch?v=MEg-oqI9qmw",
    52: "https://www.youtube.com/watch?v=Jtauh8GcxBY",
    53: "https://www.youtube.com/watch?v=rXF9ziZ3AU4",
    54: "https://www.youtube.com/watch?v=I4VVUPyb4MM",
    55: "https://www.youtube.com/watch?v=XeLaiL9tk68",
    56: "https://www.youtube.com/watch?v=VbfpW0pbvaU",
    57: "https://www.youtube.com/watch?v=TTOPBQhrvtQ",
    58: "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
    59: "https://www.youtube.com/watch?v=Sk-U8ruIQyA",
    60: "https://www.youtube.com/watch?v=25ROFXjoaAU",
    61: "https://www.youtube.com/watch?v=3AtDnEC4zak",
    62: "https://www.youtube.com/watch?v=t_dLoOXy8PA",
    63: "https://www.youtube.com/watch?v=X86gFiPkVJo",
    64: "https://www.youtube.com/watch?v=k1BneeJTDcU",
    65: "https://www.youtube.com/watch?v=EPMhkIiapIA",
    66: "https://www.youtube.com/watch?v=M-P4QBt-FWw",
    67: "https://www.youtube.com/watch?v=gm3-m2CFVWM",
    68: "https://www.youtube.com/watch?v=Axljp2Ghr3s",
    69: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    70: "https://www.youtube.com/watch?v=tt2k8PGm-TI",
    71: "https://www.youtube.com/watch?v=xtoHuHgS9_o",
    72: "https://www.youtube.com/watch?v=jJPMnTXl63E",
    73: "https://www.youtube.com/watch?v=D9G1VOjN_84",
    74: "https://www.youtube.com/watch?v=QGJuMBdaqIw",
    75: "https://www.youtube.com/watch?v=LHCob76kigA",
    76: "https://www.youtube.com/watch?v=9bZkp7q19f0",
    77: "https://www.youtube.com/watch?v=IPXIgEAGe4U",
    78: "https://www.youtube.com/watch?v=GNtIvGrqAZE",
    79: "https://www.youtube.com/watch?v=mRD0-GxqHVo",
    80: "https://www.youtube.com/watch?v=AByfaYcOm4A",
    81: "https://www.youtube.com/watch?v=L3wKzyIN1yk",
    82: "https://www.youtube.com/watch?v=ZbZSe6N_BXs",
    83: "https://www.youtube.com/watch?v=T3E9Wjbq44E",
    84: "https://www.youtube.com/watch?v=ox4tmEV6-QU",
    85: "https://www.youtube.com/watch?v=cEin6Kix6xs",
    86: "https://www.youtube.com/watch?v=2zvd1JQ0EKY",
    87: "https://www.youtube.com/watch?v=dhYOPzcsbGM",
    88: "https://www.youtube.com/watch?v=1oh33WB-pqg",
    89: "https://www.youtube.com/watch?v=np02phdwrwk",
    90: "https://www.youtube.com/watch?v=CevxZvSJLk8",
    91: "https://www.youtube.com/watch?v=Qskm9MTz2V4",
    92: "https://www.youtube.com/watch?v=2KBFD0aoZy8",
    93: "https://www.youtube.com/watch?v=s_x76GztTQE",
    94: "https://www.youtube.com/watch?v=PEnJbjBuxnw",
    95: "https://www.youtube.com/watch?v=JRfuAukYTKg",
    96: "https://www.youtube.com/watch?v=HWjCStB6k4o",
    97: "https://matias.me/nsfw/?fbclid=PAAaZCfzc_Hkpx6Gv88S-maEeNLTL7cQjFBqiCrRm-RomZOTa3qvVyCO_8dFw_aem_AfgXijsz0xZ-Zst2E3RWgEHcHFwVBOdhLwsRrzOOlMjD_-mKNxhafK_JkuXaDY0tdVQ",
}

function getRandomNumber(min, max){
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function redirect(){
    var min = 1
    var max = Object.keys(numToUrl).length
    var randomNumber = getRandomNumber(min, max);
    var url = numToUrl[randomNumber];
    window.location.href = url;
}

document.getElementById("button").addEventListener("click", redirect)
